route:
  receiver: default
  routes:
    - matchers: [ severity="critical" ]
      receiver: critical
    - matchers: [ severity="warning" ]
      receiver: warning

receivers:
  - name: default
    webhook_configs:
      - url: http://uncomplicated-alert-receiver:8080/alerts
  - name: critical
    webhook_configs:
      - url: http://uncomplicated-alert-receiver:8080/alerts
  - name: warning
    webhook_configs:
      - url: http://uncomplicated-alert-receiver:8080/alerts
